-- Run this in Supabase SQL Editor to create the table

CREATE TABLE public.submissions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    scheme text NOT NULL,
    mobile text,
    aadhar text,
    fields jsonb DEFAULT '{}'::jsonb,
    
    -- Optional: Add status column
    status text DEFAULT 'pending'
);

-- Enable Row Level Security (RLS) is good practice, 
-- but for this Hackathon demo we can allow public insert/select 
-- or you can disable RLS in the table settings.

-- Policy to allow anyone to insert (if you enable RLS)
-- CREATE POLICY "Enable insert for all" ON public.submissions FOR INSERT WITH CHECK (true);

-- Policy to allow anyone to read (if you enable RLS)
-- CREATE POLICY "Enable read for all" ON public.submissions FOR SELECT USING (true);
